version: '3.7'
networks:
  backend:
    name: app
    driver: bridge
volumes:
  postgres-data:
        
services:
  sergiopostgresdb:
    image: "postgres:13"
    container_name: sbdwpostgres-db
    restart: always
    volumes:
       - ./postgres-data:/var/lib/dwpostgresql/data
       - ./sqlscripts/inittable.sql:/docker-entrypoint-initdb.d/inittable.sql
    networks:
      - backend
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: sergiob
      POSTGRES_USER: sergiob
      POSTGRES_PASSWORD: sergioUnix1
      PGDATA: /var/lib/postgresql/pgdata
      
  app:
    build: 
      context: .
      dockerfile: dwPayloadDockerfile
    ports:
      - "8080:8080"
    networks:
      - backend
    environment:
      POSTGRES_URL: jdbc:postgresql://sergiopostgresdb/sergiob
      POSTGRES_USERNAME: sergiob
      POSTGRES_PASSWORD: sergioUnix1  
    depends_on:
      - sergiopostgresdb
  
